version: "2"

services:
  
  app:
    container_name: app_test
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - "3002:3002"
    links:
      - mongo
    command: nodemon server.js

  mongo:
    container_name: mongo_test
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - './data:/data'
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null
